version: "3.2"

services:
    # web
    nginx:
        build:
            context: ./nginx
            dockerfile: "Dockerfile"
        container_name: nginx
        ports:
            - "${NGINX_HOST_HTTP_PORT}:80"
            - "${NGINX_HOST_HTTPS_PORT}:443"
        volumes:
            #server配置
            - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
            #日志
            - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
            - ${NGINX_CONF}:/etc/nginx/nginx.conf
        networks:
            - frontend
            - backend
   
    traefik:
        build:
            context: ./traefik
            dockerfile: "Dockerfile"
        container_name: traefik
        ports:
            - "${TRAEFIK_HTTP_PORT}:80"
            - "${TRAEFIK_HTTPS_PORT}:443"
            - "${TRAEFIK_DASHBOARD_PORT}:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - ${TRAEFIK_CONF}:/etc/traefik/traefik.toml
            - ${TRAEFIK_LOG_PATH}:/var/log
        networks:
            - frontend
            - backend

    whoami:
        # A container that exposes an API to show its IP address
        image: traefik/whoami
        scale: 3
        labels:
            - "traefik.http.routers.whoami.rule=Host(`whoami.docker.local`)"

networks:
    backend:
        external:
            name: "backend"
    frontend:
        external:
            name: "frontend"
