version: "3.2"

services:
    # web
    nginx:
        build:
            context: ./nginx
            dockerfile: "Dockerfile"
        ports:
            - "${NGINX_HOST_HTTP_PORT}:80"
            - "${NGINX_HOST_HTTPS_PORT}:443"
        volumes:
            #server配置
            - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
            #日志
            - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
            - ${NGINX_CONF}:/etc/nginx/nginx.conf
        networks:
            - frontend
            - backend

networks:
    backend:
        external:
            name: "backend"
    frontend:
        external:
            name: "frontend"
