version: "3.2"

services:
    app:
        build: 
            context: ./app
            args: 
                - GO_VERSION=${GO_VERSION}
                - USE_CHINA_PROXY=${USE_CHINA_PROXY}
        volumes:
            - ${APPLICATION_HOME}:/var/www
            - ${SSH_CONFIG}:/root/.ssh
        networks:
            - backend

networks:
    backend:
        external: 
            name: "backend"
