version: "3.2"

services:
    frontend:
        build: 
            context: ./
            args: 
                - NODE_VERSION=${NODE_VERSION}
                - USE_CHINA_PROXY=${USE_CHINA_PROXY}
        volumes:
            - ${APPLICATION_HOME}:/var/www
            - ${SSH_CONFIG}:/root/.ssh
        networks:
            - frontend

networks:
    frontend:
        external: 
            name: "frontend"
