version: "3.2"

services:
    app:
        build: 
            context: ./app
            args: 
                - JAVA_VERSION=${JAVA_VERSION}
                - USE_CHINA_PROXY=${USE_CHINA_PROXY}
                - INSTALL_MAVEN=${INSTALL_MAVEN}
                - INSTALL_GRADLE=${INSTALL_GRADLE}
                - GRADLE_VERSION=${GRADLE_VERSION}
                - MAVEN_VERSION=${MAVEN_VERSION}
        volumes:
            - ${APPLICATION_HOME}:/var/www
            - ${SSH_CONFIG}:/root/.ssh
        networks:
            - backend

networks:
    backend:
        external: 
            name: "backend"
