version: "3.2"

services:
    elasticsearch:
        build:
            context: ./elasticsearch
            args:
                - ES_VERSION=${ES_VERSION}
            dockerfile: "Dockerfile"
        hostname: elasticsearch
        ports:
            - "${ES_INDEX_PORT}:9200"
        environment:
            - http.host=0.0.0.0
            - transport.host=127.0.0.1
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms${ES_JVM_HEAP} -Xmx${ES_JVM_HEAP}"
        mem_limit: ${ES_MEM_LIMIT}
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - esdata:/usr/share/elasticsearch/data
            - ./elasticsearch/logs:/usr/share/elasticsearch/logs
        networks:
            - backend

    kibana:
        build:
            context: ./kibana
            args:
                - KIBANA_VERSION=${KIBANA_VERSION}
            dockerfile: "Dockerfile"
        ports:
            - "${KIBANA_PORT}:5601"
        depends_on:
            - elasticsearch
        networks:
            - backend
        # environment:
        #     - "ELASTICSEARCH_PASSWORD=${ES_PASSWORD}"

volumes:
    esdata:
        driver: local

networks:
    backend:
        external: 
            name: "backend"
