# enable Docker Configuration Backend
[providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    defaultRule = "Host(`{{ normalize .Name }}.docker.localhost`)"

# Entry Definition
[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.websecure]
    address = ":443"

# Enable API and Dashboard
[api]
   insecure = true
   dashboard = true

# Enable Log to stdout
[log]
   level = "ERROR"
   filePath = "/var/log/traefik.log"
   format = "json"
[accessLog]
   filePath = "/var/log/access.log"
   format = "json"