version: "3.2"

services:
    app:
        build: 
            context: ./app
            args: 
                - PHP_VERSION=${PHP_VERSION}
                - INSTALL_GRPC=${INSTALL_GRPC}
                - INSTALL_REDIS=${INSTALL_REDIS}
                - INSTALL_GD=${INSTALL_GD}
                - INSTALL_XDEBUG=${INSTALL_XDEBUG}
                - XDEBUG_VERSION=${XDEBUG_VERSION}
                - REDIS_VERSION=${REDIS_VERSION}
                - USE_CHINA_PROXY=${USE_CHINA_PROXY}
        volumes:
            - ${APPLICATION_HOME}:/var/www
            - ${SSH_CONFIG}:/root/.ssh
            - composecache:/tmp
        networks:
            - backend

volumes:
    composecache:
        driver: local

networks:
    backend:
        external: 
            name: "backend"
